# Generated by Django 4.0.3 on 2022-03-10 01:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('header', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_row', models.CharField(max_length=1024)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='TemporalProcessor.file')),
            ],
        ),
        migrations.CreateModel(
            name='Temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('column', models.IntegerField()),
                ('startIdx', models.IntegerField()),
                ('endIdx', models.IntegerField()),
                ('text', models.CharField(max_length=256)),
                ('temporal', models.CharField(max_length=256)),
                ('type', models.CharField(default='', max_length=64)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporals', to='TemporalProcessor.file')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporals', to='TemporalProcessor.row')),
            ],
        ),
    ]
